export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

export const TOGGLE_BASKET_VISIBLE = 'CART_VISIBLE';
export const ADD_ITEM_BASKET = 'ADD_ITEM_CART';
export const CLEAR_ITEM_FROM_BASKET = 'CLEAR_ITEM_FROM_CART';
export const CLEAR_BASKET = 'CLEAR_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
